DROP TABLE IF EXISTS PERSONS;

CREATE TABLE Persons (
    ID int NOT NULL,
    LASTNAME varchar(255)CHECK (LASTNAME != 'fazil'),
    FIRSTNAME varchar(255) CHECK (FIRSTNAME != LASTNAME),
    AGE int CHECK (AGE>=18),
    PRIMARY KEY (ID)
);
