DROP TABLE IF EXISTS PERSONS;

CREATE TABLE PERSONS
(ID int NOT NULL, LASTNAME VARCHAR(255) NOT NULL, FIRSTNAME VARCHAR(255) , AGE int , PRIMARY KEY (ID))

CREATE OR REPLACE FUNCTION PERSONS_check_function()
  RETURNS TRIGGER
  LANGUAGE PLPGSQL
  AS
  $$
  BEGIN
	  IF NEW.FIRSTNAME != NEW.LASTNAME THEN
		   return NULL
	  END IF;
	  IF NEW.AGE >= 18 THEN
		   return NULL
	  END IF;
	  RETURN NEW;
  END;
  $$

CREATE TRIGGER PERSONS_check_trigger
BEFORE INSERT ON PERSONS
  FOR EACH ROW EXECTURE FUNCTION PERSONS_check_function
