DROP TABLE IF EXISTS PERSONS;

CREATE TABLE PERSONS
(ID int NOT NULL, LASTNAME VARCHAR(255) NOT NULL , FIRSTNAME VARCHAR(255) , AGE int , PRIMARY KEY (ID));

CREATE OR REPLACE FUNCTION PERSONS_0_check_function()
  RETURNS TRIGGER
  LANGUAGE PLPGSQL
  AS
  $$
  BEGIN
	  IF (NEW.LASTNAME != 'fazil' OR NEW.LASTNAME != "jim" OR NEW.LASTNAME != "wen hao" ) THEN
		   return NEW;
	  END IF;
	  RETURN NULL;
  END;
  $$;

CREATE TRIGGER PERSONS_0_check_trigger
BEFORE INSERT ON PERSONS
  FOR EACH ROW EXECUTE FUNCTION PERSONS_0_check_function();


CREATE OR REPLACE FUNCTION PERSONS_1_check_function()
  RETURNS TRIGGER
  LANGUAGE PLPGSQL
  AS
  $$
  BEGIN
	  IF NEW.FIRSTNAME != NEW.LASTNAME THEN
		   return NEW;
	  END IF;
	  RETURN NULL;
  END;
  $$;

CREATE TRIGGER PERSONS_1_check_trigger
BEFORE INSERT ON PERSONS
  FOR EACH ROW EXECUTE FUNCTION PERSONS_1_check_function();


CREATE OR REPLACE FUNCTION PERSONS_2_check_function()
  RETURNS TRIGGER
  LANGUAGE PLPGSQL
  AS
  $$
  BEGIN
	  IF NEW.AGE >= 18 THEN
		   return NEW;
	  END IF;
	  RETURN NULL;
  END;
  $$;

CREATE TRIGGER PERSONS_2_check_trigger
BEFORE INSERT ON PERSONS
  FOR EACH ROW EXECUTE FUNCTION PERSONS_2_check_function();
