DROP TABLE IF EXISTS PERSONS;

CREATE TABLE PERSONS
(ID int NOT NULL, LASTNAME VARCHAR(255) NOT NULL , FIRSTNAME VARCHAR(255) , AGE int , PRIMARY KEY (ID));

CREATE OR REPLACE FUNCTION PERSONS__check_function()
  RETURNS TRIGGER
  LANGUAGE PLPGSQL
  AS
  $$
  BEGIN
	  IF (NEW.LASTNAME != 'fazil' OR NEW.LASTNAME != 'jim' OR NEW.LASTNAME != 'wen hao' ) AND NEW.FIRSTNAME != NEW.LASTNAME AND NEW.AGE >= 18 THEN
		   return NEW;
	  END IF;
	  RETURN NULL;
  END;
  $$;

CREATE TRIGGER PERSONS__check_trigger
BEFORE INSERT ON PERSONS
  FOR EACH ROW EXECUTE FUNCTION PERSONS__check_function();
